config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :addresses
  resources :orders
  resources :products
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/cart', to: 'carts#remove_item', as: 'remove_item'

root 'static_pages#home'
get '/signup', to: 'users#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'

resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products
  has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
  has_many :products, through: :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product 
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :category_products
  has_many :categories, through: :category_products
  has_many :order_products
  has_many :images
  has_many :orders, through: :order_products
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token

  before_save {self.email = email.downcase}

  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}


  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def cart
    session[:cart] ||= []
  end

  def add_to_cart
    # Get the item from the path
    @product = Product.find(params[:id])
    # Load the cart from the session, or create a new empty cart.
    cart << @product.id
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @cart = cart
  end

  def create
    @cart = cart
    add_to_cart
    redirect_to carts_path
  end

  def remove_item
    cart.delete_at(cart.find_index(params[:id].to_i))
    redirect_to carts_path
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

   def new
     @cart = cart

     @order = Order.new
   end

   def create
     @order = Order.create(order_params)


     redirect_to @order
   end

  def show
    @order = Order.find(params[:id])
  end



  private

  def order_params
    params.require(:order).permit(:street, :city, :state, :zip)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to root_path
    end
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in user
      params[:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or(user)
    else
      flash.now[:danger] = "Invalid email or password!"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to your HeroApp Profile!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end


  def log_out
    forget(current_user)
    session.clear
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/views/carts/index.html.erb
<center><h2>Your Cart</h2></center>
<% @cart.each do |product_id| %>
  <% p = Product.find(product_id) %>
  <img src=<%= p.images.first[:image_url] %> height="100" width="100">
  <p style="font-size: 25px;">
    <%= p[:name] %>
    <br>
  $<%= p[:price].to_f.round(2) %>
  </p>
  <%= form_tag remove_item_path do %>
    <%= hidden_field_tag :id, p[:id] %>
    <%= button_tag "Remove From Cart", class: 'btn btn-primary' %>
  <% end %>

  <br>
<% end %>
<p style="font-size: 25px;">

Total Price:
<% total_price = 0.00 %>
<% @cart.each do |product_id| %>
  <% p = Product.find(product_id) %>
  <% total_price += p[:price].round(2) %>
<% end %>

<% if total_price.to_s.length < 4 %>
  $<%= total_price.to_s + "0" %>
<% else %>
  $<%=  total_price  %>
<% end %>

<%= link_to "Checkout", new_order_path%>
</p>

app/views/carts/show.html.erb
<h4>Your Cart</h4>
<% @cart.each do |p| %>
<img src=<%= p["image_url"] %> alt="image" height="100" width="100">
<%= p["name"] %>
$<%= p["price"].to_f.round(2) %>
<br>
<% end %>
Total Price:
<% total_price = 0.00 %>
<% @cart.each do |p| %>
  <% total_price += p["price"].to_f.round(2) %>
<% end %>
$<%= total_price.round(2) %>

<%= link_to "Checkout", new_order_path %>

app/views/categories/index.html.erb
<center><h2>Categories</h2></center>

</ul>
<div class="list-group">
  <% @categories.each do |c| %>
  <a href=<%= category_path(c.id) %> class="list-group-item list-group-item-action">
    <img src=<%= c.image_url %> class="mr-3" height="100" width="100">
    <b style='font-size:30px;padding-left:60px;'><%=c.name %></b>
     <span class="badge badge-primary badge-pill"><%= c.products.count %></span>
  </a>
  <% end %>
</div>

app/views/categories/show.html.erb
<center><h2><%= @category.name %></h2></center>
</ul>
<div class="list-group">
  <% @category.products.each do |c| %>
  <a href=<%= product_path(c.id) %> class="list-group-item list-group-item-action">
    <img src=<%= c.images.first[:image_url] %> class="mr-3" height="100" width="100">
    <b style='font-size:15px;padding-left:60px;'><%=c.name %></b>
    <b style='font-size:15px;padding-left:60px;'>$ <%=c.price.round(2) %></b>
  </a>
  <% end %>
</div>

app/views/orders/new.html.erb
<h2>Checkout Page</h2>
<% @cart.each do |product_id| %>
  <% p = Product.find(product_id) %>
  <img src=<%= p.images.first[:image_url] %> alt="image" height="100" width="100">
  <%= p[:name] %>
  $<%= p[:price].to_f.round(2) %>
  <br>
<% end %>
Total Price:
<% total_price = 0.00 %>
<% @cart.each do |product_id| %>
  <% p = Product.find(product_id) %>
  <% total_price += p[:price].to_f.round(2) %>
<% end %>
$<%= total_price.round(2) %>

  <%= form_for @order do |f| %>
    <%= f.label :street %>
    <br>
    <%= f.text_field :street %>
    <br>
    <%= f.label :city %>
    <br>
    <%= f.text_field :city %>
    <br>
    <%= f.label :state %>
    <br>
    <%= f.text_field :state %>
    <br>
    <%= f.label :zip %>
    <br>
    <%= f.text_field :zip %>
    <br>
    <%= f.button %>

  <% end %>

app/views/orders/show.html.erb
<h4>Order Confirmed</h4>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<center>
  <% @product.images.each do |i| %>
    <img src=<%= i[:image_url] %> alt="image" height="200" width="200" class="img-thumbnail">
  <% end %>
  </center>
  <% @product.description%>
  <br>
  <p style="font-size: 30px;">
  <b>Price:</b> $<%= @product.price.round(2) %>
  <br>
  <b>Shipping Time:</b> <%= @product.shipping_time %> days</p>
  <%= form_tag carts_path do %>
    <%= hidden_field_tag :id, @product.id %>
    <%= button_tag "Add to Cart", class: 'btn btn-primary'%>
  <% end %>